const CONFIG = {
  // Wallet addresses
  WALLETS: {
    NEW_DEPLOYER_ADDRESS: process.env.NEW_DEPLOYER_ADDRESS,
    GENERAL_ADMIN: process.env.GENERAL_ADMIN_WALLET,
    USER_MANAGER: process.env.USER_MANAGER_WALLET,
    USER_2FA: process.env.USER_2FA_WALLET,
    MASTER_ADMIN: process.env.MASTER_ADMIN_WALLET
  },

  // External contract addresses
  EXTERNAL: {
    UNISWAP_NFT: process.env.UNISWAP_NFT_ADDRESS,
    SWAP_ROUTER: process.env.SWAP_ROUTER_ADDRESS,
    FACTORY: process.env.FACTORY_ADDRESS,
    MAIN_TOKEN: process.env.MAIN_TOKEN_ADDRESS,
    CLIENT: process.env.CLIENT_ADDRESS
  },

  // Protocol values
  PROTOCOL: {
    BASE_POINT: 10000,
    COMPANY_FEE_PCT: 3000,
    CLIENT_FEE_PCT: 5000,
    MAX_ROLES_SIZE: 10,
    MIGRATION_SIZE: 150,
    MAX_WITHDRAWAL_SIZE: 150
  },

  // Salt prefixes for CREATE3
  SALTS: {
    USER_MANAGER: "USER_MANAGER_V1_MAIN_PROXY",
    PROTOCOL_CONFIG: "PROTOCOL_CONFIG_V1_MAIN_PROXY",
    VAULT: "VAULT_V1_MAIN_PROXY",
    LIQUIDITY_MANAGER: "LIQUIDITY_MANAGER_V1_MAIN_PROXY",
    LIQUIDITY_HELPER: "LIQUIDITY_HELPER_V1_MAIN_PROXY",
    ORACLE_SWAP: "ORACLE_SWAP_V1_MAIN_PROXY",
    AGGREGATOR: "AGGREGATOR_V1_MAIN_PROXY"
  }
};

module.exports = CONFIG;